development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://mwmojdzhndcrii:ff04c28b51bd3f4834ad7eb0e2bf3d8f3b11d05d7e533d65ffce016cd1e5fe56@ec2-107-22-167-179.compute-1.amazonaws.com:5432/d9nr10ifubr7j2
  channel_prefix: nameofapp_production
